name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  GO111MODULE: on

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
        go: [1.21]
    name: Test @ Go ${{ matrix.go }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up Go ${{ matrix.go }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}

      - uses: actions/checkout@v4

      - uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Run linters
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin
          golangci-lint run
      - name: Run Tests
        run: |
          go test -race --coverprofile=coverage.coverprofile ./...
      - name: Upload coverage to Codecov
        if: success() && matrix.go == 1.21 && matrix.os == 'ubuntu-latest'
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: false
  release:
    runs-on: ubuntu-latest
    needs: [test]
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          command: manifest
